config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'calendar/index'

  devise_for :users
  get 'home/index'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper :application
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.where(start: params[:start]..params[:end])
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
  end

  def update
    @event.update(event_params)
  end

  def destroy
    @event.destroy
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :date_range, :start, :end, :color)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(text, link)
    recognized = Rails.application.routes.recognize_path(link)
    if recognized[:controller] == params[:controller] && recognized[:action] == params[:action]
      content_tag(:li, :class => "active") do
        link_to( text, link)
      end
    else
      content_tag(:li) do
        link_to( text, link)
      end
    end
  end

end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/calendar/index.html.slim
#img-banners
  #jazz5
  #jazz6   

.container
  .row
    .col-sm-12
      h1 Jazz Collective of Utah Calendar
      hr
      p Check out the calendar below to see upcoming events sponsored by the collective
      p Suggest an event for the Collective by adding it to the calendar below

.container
  .row
    .col-sm-12
      .calendar

app/views/events/_edit.html.slim
#edit_event.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  &times;
        h4.modal-title Edit Event
      .modal-body
		    =render 'form', event: @event

app/views/events/_form.html.slim
=simple_form_for @event, remote: true do |f|
  .form-inputs
    =f.input :title, input_html: { class: 'form-control input-sm' }
    =f.input :date_range, input_html: { class: "form-control input-sm date-range-picker" }
    =f.input_field :start, as: :hidden, value: Date.today, class: 'form-control input-sm start_hidden'
    =f.input_field :end, as: :hidden, value: Date.today, class: 'form-control input-sm end_hidden'
    =f.input :color, as: :select, collection: [['Black','black'], ['Green','green'], ['Red','red']], input_html: { class: 'form-control input-sm' }
  .form-actions
    =f.button :submit, class: 'btn btn-default'
    =link_to 'Delete Event',
      event,
      method: :delete,
      class: 'btn btn-danger',
      id: 'delete-button',
      remote: true unless @event.new_record?
end

app/views/events/_new.html.slim
#new_event.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  &times;
        h4.modal-title Create New Event
      .modal-body
		    =render 'form', event: @event

app/views/events/create.js.erb
$('.calendar').fullCalendar(
  'renderEvent',
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');

app/views/events/destroy.js.erb
$('.calendar').fullCalendar('removeEvents', [<%= @event.id %>])
$('.modal').modal('hide');

app/views/events/edit.html.slim
h1 Editing event

== render 'form'

= link_to 'Show', @event
'  |
= link_to 'Back', events_path

app/views/events/edit.js.erb
$('#remote_container').html('<%= j render "edit" %>');
$('#edit_event').modal('show');

app/views/events/index.html.slim
h1 Listing events

table
  thead
    tr
      th Date
      th Date
      th Start
      th End
      th Title
      th Description
      th String
      th
      th
      th

  tbody
    - @events.each do |event|
      tr
        td = event.date
        td = event.date
        td = event.start
        td = event.end
        td = event.title
        td = event.description
        td = event.string
        td = link_to 'Show', event
        td = link_to 'Edit', edit_event_path(event)
        td = link_to 'Destroy', event, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Event', new_event_path

app/views/events/new.html.slim
h1 New event

== render 'form'

= link_to 'Back', events_path

app/views/events/new.js.erb
$('#remote_container').html('<%= j render "new" %>');
$('#new_event').modal('show');

app/views/events/show.html.slim
p#notice = notice

p
  strong Date:
  = @event.date
p
  strong Date:
  = @event.date
p
  strong Start:
  = @event.start
p
  strong End:
  = @event.end
p
  strong Title:
  = @event.title
p
  strong Description:
  = @event.description
p
  strong String:
  = @event.string

= link_to 'Edit', edit_event_path(@event)
'  |
= link_to 'Back', events_path

app/views/events/update.js.erb
$('.calendar').fullCalendar('removeEvents', [<%= @event.id %>]);
$('.calendar').fullCalendar(
  'renderEvent',
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');

app/views/home/index.html.slim
#banner
    
.container
  .row
    .col-md-12
      #title.text-center
        h1 Let Your Voice Be Heard
      p.lead The Jazz Collective of Utah brings musicians, students, educators, and jazz enthusiasts together as one community and allows presenters to connect with fans and students in a meaningful way so that everyone benefits. It is home to Utah’s new Jazz Education Network (JEN) State Unit launching this summer. Additionally, the JCU is poised to lobby for the arts in our community, fund scholarships, host training for educators, present clinics for students, host listening events, present festivals, serve as a jazz society, and much more!
      button.btn.btn-default.center-block = link_to 'Check Out Upcoming Events', calendar_index_path

#img-banners-1
  #jazz1
  #jazz2
  
.container-fluid
  .row.text-center
    .col-sm-4
      i.glyphicon.glyphicon-music.callout-icon
      h3.callouts Music Comes First
      p.lead We are committed first and foremost to making great music, and building great musicians
    .col-sm-4
      i.glyphicon.glyphicon-sort.callout-icon
      h3.callouts Learn From The Pros
      p.lead This is the place to network with the people who are making a living playing jazz in Utah
    .col-sm-4
      i.glyphicon.glyphicon-volume-up.callout-icon
      h3.callouts Find Your Voice
      p.lead The Jazz Collective of Utah gives a unique opportunity for young people to have their voices heard like never before 

#img-banners-2
  #jazz3
  #jazz4

app/views/layouts/application.html.slim
doctype html
html
  head
    title Jazz Collective of Utah
    = favicon_link_tag
    = csrf_meta_tags()
    meta content="width=device-width, initial-scale=1" name="viewport"
    = stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track': 'reload')
    = javascript_include_tag('application', 'data-turbolinks-track': 'reload')
    link href="https://fonts.googleapis.com/css?family=Work+Sans:400,600" rel="stylesheet"

  body
    nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href=url_for(home_index_path)
            i.glyphicon.glyphicon-music.larger 
            | Jazz Collective of Utah
        .collapse.navbar-collapse.navbar-ex1-collapse
          ul.nav.navbar-nav.navbar-right
            li = nav_link 'Home', home_index_path
            li = nav_link 'Calendar', calendar_index_path

            - if current_user
              li.dropdown
                a.dropdown-toggle data-toggle="dropdown" href="#" 
                  | Hello &nbsp;
                  = current_user.email
                  span.caret
                ul.dropdown-menu role="menu" 
                  li = link_to('Change Password', edit_user_registration_path)
                  li = link_to('Logout', destroy_user_session_path, :method => :delete)
            - else
              li = nav_link 'Login', new_user_session_path

    = yield
    #remote_container

    footer.text-center
      .container
        p Copyright &copy; 2017 - Jazz Collective of Utah